language: ruby
rvm:
  - 2.6.5
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - yarn
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake
cache:
  bundler: true
  yarn: true
