default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: dinnerpal
  password: password
  host: localhost

development:
  <<: *default
  database: dinnerpal_dev

test:
  <<: *default
  database: dinnerpal_test

production:
  <<: *default
  database: dinnerpal_prod
